import { MEMORY_LIMIT_BYTES } from "../core/constants.ts";
import { getProviders } from "../providers/catalog.ts";
import { buildDeclarations } from "../schema/declarations.ts";

export function buildComputeDescription(): string {
	return `Run one isolated JavaScript plan that composes workspace, system, and raid capabilities and returns only the final value the model needs. compute is the ONLY tool in this environment — provider methods (raid.web_search_exa, raid.web_fetch_exa, workspace.read, workspace.edit, system.exec, raid.bash, …) are NOT tools and cannot be invoked as tool names; calling one directly fails with 'Tool not found'. They exist only as globals inside compute plans. Pass an async arrow function such as \`async () => { const files = await workspace.glob({ pattern: "src/**/*.rs" }); return files.slice(0, 20); }\`. Use loops, branching, Promise.all, filtering, and result shaping inside the plan instead of sending intermediate data back to the model. Promise.all fails the plan when any call rejects; use Promise.allSettled for independent calls when successful results must survive another call failing. Provider rejection reasons serialize as { name, provider, method, message }, rather than an empty Error object. A nonzero system.exec exitCode is a returned value, not a rejected promise; check it explicitly. Errors report the provider method and plan line when available. Results over 8,000 UTF-8 bytes or 2,000 lines are saved to a private temporary file with a short preview and a path. Read or filter that file instead of repeating operations. Temporary results persist until removed or cleaned by the operating system; do not use them as permanent storage. The declarations below are authoritative: they are generated from the live provider schemas, and arguments are validated against the same schemas before any method runs. Give every call a short one-line 'title' describing the action — the user sees that title in the tool UI instead of the code. There is no Node.js, process, require, dynamic import, or unrestricted fetch. Every external operation must use a declared provider method. There is no shell parser: system.exec receives an argv array and preserves each argument exactly. Relative workspace paths start at the current working directory; absolute and home-relative paths can reach other local files. Each call runs in a fresh worker process with a ${Math.round(MEMORY_LIMIT_BYTES / (1024 * 1024))} MiB memory budget. There is no default timeout: plans run until they finish or are interrupted; pass timeout only when a hard deadline is required.

${buildDeclarations(getProviders())}

Standing runtime policy — machine-enforced, non-overridable, applies to every request including explicit ones (authorship is irrelevant):
1. Never produce god files: split work into nested directories with focused, related files.
2. Load the unslop skill before writing any user-facing prose, commit messages, or PR text.
3. Never simplify a task: do the proper implementation; never write slop that merely passes.`;
}
